### ISSUE TITLE
Issues in the document

### ISSUE THREAD

**Issue by ChenYangyao** [ChenYangyao/hipp#5]
The example in [io for built-in type](https://github.com/ChenYangyao/hipp/blob/dev/docs/usage/tutorial/io/basic_usage/read_write_built_in_data.rst):
```
auto data_ptr = std::make_shared<int>(521);
o_h5.create_dataset<int>("another_data", {521}).write(data_ptr.get());
```
must be wrong.

**Comment by wkcosmology** [comment]
Thanks! I modified the doc accordingly.
