### ISSUE TITLE
let `str_f` accept `std::string` as its first parameter

### ISSUE THREAD

**Issue by wkcosmology** [ChenYangyao/hipp#67]
Currently, `HIPP::str_f` only accepts `const char *` as its first parameter. If I have a `std::string`, I need to use `.c_str()` method to convert it to `const char *` first.
I was wondering if we can add an overload function that accepts the `std::string` as its first parameter.

**Comment by ChenYangyao** [comment]
The overload has been added.

**Comment by ChenYangyao** [comment]
Problem solved.
